SET COLSEP '||'
SET PAGESIZE 99
SET LINESIZE 150
COLUMN ESTUDIANTE FORMAT A17;
COLUMN CURSO FORMAT A17;
COLUMN INSTRUCTOR FORMAT A17;
DROP TABLE GRUPO_MATERIA;
DROP TABLE INSTRUCTOR_CURSO;
DROP TABLE INSTRUCTOR_ESTUDIANTE;

CREATE TABLE GRUPPO_MATERIA (
	ESTUDIANTE VARCHAR2(16),
		CURSO 	VARCHAR2(16),
		INSTRUCTOR VARCHAR(16));
CREATE TABLE INSTRUCTOR_CURSO(
	INSTRUCTOR VARCHAR2(16),
		CURSO  VARCHAR2(16));
CREATE TABLE INSTRUCTOR_ESTUDIANTE(
	INSTRUCTOR  VARCHAR(16),
		ESTUDIANTE VARCHAR2(16));

INSERT INTO GRUPO_MATERIA VALUES('MACLOVIA','BASES DE DATOS', 'Martinez');
INSERT INTO GRUPO_MATERIA VALUES('MANUEL','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('MARCELO','Sist Operativos','Omar');
INSERT INTO GRUPO_MATERIA VALUES('MARCOS','T de Automatas','Shaums');
INSERT INTO GRUPO_MATERIA VALUES('MARGARITA','BASES DE DATOS','Martinez');
INSERT INTO GRUPO_MATERIA VALUES('MARIA','Sist Operativos','Araujo');
INSERT INTO GRUPO_MATERIA VALUES('MARIANA','BASES DE DATOS','Lopez');
INSERT INTO GRUPO_MATERIA VALUES('MARTIN','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('MATEO','Sist Operativos','Omar');

SELECT * FROM GRUPO_MATERIA;
--INSERT INTO INSTRUCTOR_CURSO SELECT INSTRUCTOR, CURSO FROM 
GRUPO_MATERIA;

INSERT INTO INSTRUCTOR_CURSO SELECT DISTINCT (INSTRUCTOR), CURSO FROM GRUPO_MATERIA;

INSERT INTO INSTRUCTOR_ESTUDIANTE SELECT INSTRUCTOR, ESTUDIANTE FROM GRUPO_MATERIA;
SELECT COUNT(*) FROM GRUPO_MATERIA;
SELECT * FROM GRUPO_MATERIA ORDER BY 3,2,1;
SELECT * FROM INSTRUCTOR_ESTUDIANTE ORDER BY 1,2;
SELECT * FROM INSTRUCTOR_CURSO ORDER BY 1.2;
DELETE FROM INSTRUCTOR_ESTUDIANTE;
DELETE FROM INSTRUCTOR_CURSO;
PROMPT ADICIONAR TODOS LOS ALUMNOS Araujo
PROMPT ADICIONAR TODOS LOS ALUMNOS DE NAVATHE

INSERT INTO GRUPO_MATERIA VALUES('AARON','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ABEL','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ABIGAIL','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ABRAHAM','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ABRIL','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADALBERTO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADÁN','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADELA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADELINA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADELMO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADOLFO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADRIÁN','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ADRIANO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AGATA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AGUEDA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AGUSTIN','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AÍDA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AINARA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALAN','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALBANO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALBERTO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALCIRA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALDO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALEJANDRO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALEJANDRA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALEJO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALFONSO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALFREDO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALICIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALINA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALMUDENA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALONSO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ALVARO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMADEO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMALIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMANCIO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMANDA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMARANTO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMAYA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMOS','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMBROSIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMELIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMIRA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AMPARO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANACLETO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANASTACIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANDERA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANDRÉS','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ÁNGELA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANGÉLICA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ÁNGELES','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANÍBAL','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANICETO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AGUSTIN','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANSELMO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANTONIO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANTONIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ANTONIETA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('APOLO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AQUILES','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AQUILINA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARACELI','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARCHIBADO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARIADNA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARIEL','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARÍSTIDES','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARMANDO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARNOLDO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ARTURO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ASUNCIÓN','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('ATANASIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AUGUSTO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AURELIO','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AURELIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AURORA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AUXILIA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AXEL','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('AZUZENA','SIST OPERA','ARAUJO');
INSERT INTO GRUPO_MATERIA VALUES('RAFAEL','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAIMUNDO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAMIRO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAMONA ','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAMÓN','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAQUEL','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAQUEL','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RAÚL','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('REBECA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('REINA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('REINALDO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('REGINA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('REMEDIOS','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RENATO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RENÉ','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RICARDO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RITA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROBERTO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROCÍO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RODOLFO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RODRIGO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROGELIO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROLANDO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROMÁN','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROMEO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROMILDO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROMILDA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('RONALDO','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROQUE','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROSA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROSALÍA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('ROSAMUNDA','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');
INSERT INTO GRUPO_MATERIA VALUES('','BASES DE DATOS','NAVATHE');